const poems = [
"How could I forget you when your name is always woven into the rhythm of my soul?",
"I have never seen someone like the moon and I have never seen someone like you. The moon shines the night and you shine my world.",
"Can you? When I am lying in bed at night and my mind drifts your way when my day is spent lost in your fantasy can you feel me thinking about you?",
"You make the world feel less like noise and more like music.",
"You didn’t ruin me, you just made it harder for anyone else to reach me.",
"And maybe, just maybe your heart is a garden in need of a gardener who knows how to plant hope.",
"If someone were to ask me to describe 'beauty' my first thought would be to describe you because in my eyes beauty isn’t just a word beauty is you.",
"You cross my mind in the smallest moments…",
"You mean a lot to me. Sorry if I didn’t show it in a way you needed.",
"I love you in a way you'll never notice…",
"The sunset reminds me of you.",
"I realized I still loved you…",
"I’m going to plant you like seeds in my dreams…",
"Maybe it was your laugh or your eyes or your smile…",
"I skip some songs because they sound too much like you.",
"I wanted to text you but I asked Jesus to watch over you for me.",
"I read a book I think about you…",
"If loving you is a mistake, then let me be wrong forever.",
"You're the only fish in my sea…",
"I looked at you once and the idea of forever made sense…",
"There is this tune I found that makes me think of you…",
"I dreamt about you nearly every night this week.",
"I think we are both blind…",
"My weakness isn’t a thing; it’s your eyes…",
"I want to be every word your heart feels…",
"I still don’t know what to do with all the silence you left.",
"I’ll leave the key to my heart under the mat…",
"Call me!!",
"When I miss you I experience a heartache…",
"If love had a heartbeat it would sound like your name.",
"I sleep to see you…",
"I sleep so I can see you…",
"You matter to me more than you think…",
"You are amazingly pretty.",
"You still have the prettiest brown eyes I’ve ever seen.",
"In my eyes you are the masterpiece…",
"Missing you comes in waves…",
"I dedicate the moon to you…",
"Born to love you like a poem…",
"Your smile is the sun…",
"Those beautiful brown eyes…",
"The way you laugh…",
"Every time I see you…",
"Your beauty isn’t just in your face…",
"You have the prettiest eyes…",
"Being around you is like listening to my favorite song…",
"You shine effortlessly…",
"The way you look at the world…",
"Every small thing about you feels like poetry…"
];
